### PR TITLE
Bump CoordinateTransformations compat to include 0.6

### PR DESCRIPTION
**Pull request by Octogonapus**
This PR bumps the CoordinateTransformations package compat so that it includes 0.6.

### CODE REVIEW

**Comment by kdw503** [comment]
This also same as RegisterCore documenter error issue. Thanks.

**Comment by Octogonapus** [comment]
> This also same as RegisterCore documenter error issue. Thanks.

Ok, I did the same fix here https://github.com/HolyLab/RegisterDeformation.jl/pull/17

**Comment by IanButterworth** [comment]
bump

**Comment by IanButterworth** [comment]
bump 🙏🏻

**Comment by IanButterworth** [comment]
thanks! Can we expect new versions to be registered soon too?

**Comment by kdw503** [comment]
Sure thanks!

**Comment by IanButterworth** [comment]
Great. To be complete, given there have been PRs across various repos, these need new versions

https://github.com/HolyLab/RegisterMismatch.jl
https://github.com/HolyLab/RegisterDeformation.jl
https://github.com/HolyLab/RegisterCore.jl

**Pull request merged**
